# Generated by Django 5.0.4 on 2024-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
